site_name: ckanext-blocksmith
site_url: https://datashades.github.io/ckanext-blocksmith/

repo_url:  https://github.com/DataShades/ckanext-blocksmith

theme:
  name: material
  features:
    - content.code.copy

nav:
  - Home: index.md
  - Configuration: configuration.md
  - Installation: installation.md
  - Config Settings: config_settings.md
  - Pages: pages/overview.md
  - Snippets: snippets/overview.md
  - Menus: menus/overview.md
